# Generated by Django 5.2.7 on 2025-10-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='unit_price',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AddField(
            model_name='sales',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='grand_total',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
