# Generated by Django 5.2.7 on 2025-10-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_sales_unit_price_sales_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='discount',
            field=models.FloatField(default=0.0, help_text='Discount amount applied to the total sale'),
        ),
    ]
