# Generated by Django 5.2.7 on 2025-10-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_sales_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='discount',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.FloatField(default=0.0, help_text='Discount amount applied to this product'),
        ),
    ]
