# Generated by Django 5.2.7 on 2025-10-19 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='code',
            new_name='category_code',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
    ]
