# Generated by Django 5.2.7 on 2025-10-19 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_rename_code_category_category_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='product_brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='buying_price',
            new_name='product_buying_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='product_category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='product_description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='discount',
            new_name='product_discount',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='product_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='product_quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='selling_price',
            new_name='product_selling_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sku',
            new_name='product_sku',
        ),
    ]
