# Generated by Django 5.2.7 on 2025-10-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_rename_grand_total_sales_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='buying_price',
            field=models.FloatField(help_text='How much the owner bought the product for'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.FloatField(default=0.0, help_text='Discount per item'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(help_text='How much the owner sells to customers'),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='unit_price',
            field=models.FloatField(editable=False),
        ),
    ]
