# Generated by Django 5.2.7 on 2025-10-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_alter_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
