# Generated by Django 5.2.7 on 2025-10-23 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_alter_category_category_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_quantity', models.PositiveIntegerField(editable=False)),
                ('quantity_added', models.PositiveIntegerField(help_text='Quantity to add to stock')),
                ('new_quantity', models.PositiveIntegerField(editable=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='administrator.product')),
            ],
            options={
                'verbose_name': 'Stock Record',
                'verbose_name_plural': 'Stock Records',
                'ordering': ['-added_at'],
            },
        ),
    ]
