# Generated by Django 5.2.7 on 2025-10-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_managestocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managestocks',
            name='new_quantity',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='managestocks',
            name='previous_quantity',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
