# Generated by Django 5.2.7 on 2025-10-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_rename_product_buying_price_product_product_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='selling_price',
            field=models.FloatField(default=0.0),
        ),
    ]
