# Generated by Django 5.2.7 on 2025-10-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('SALESPERSON', 'SALESPERSON')], default='ADMIN', max_length=30),
        ),
    ]
